files:
  - source: /source/**/*
    ignore:
      - _static
      - _templates
      - media
      - '*.py'
      - '*.txt'
      - /source/*.md
    translation: /%locale_with_underscore%/**/%original_file_name%
